name: 'Docker Build and Push'
description: 'Builds and pushes a Docker image'
inputs:
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
    default: 'Dockerfile'
  image_name:
    required: true
  tag:
    required: true
  registry:
    required: true
  registry_project:
    required: true
  username:
    required: true
  password:
    required: true
  context:
    description: 'Build context'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Build and Push
      shell: bash
      run: |
        echo '${{ inputs.password }}' | docker login ${{ inputs.registry }} -u '${{ inputs.username }}' --password-stdin
        FULL_IMAGE="${{ inputs.registry }}/${{ inputs.registry_project }}/${{ inputs.image_name }}:${{ inputs.tag }}"
        LATEST_IMAGE="${{ inputs.registry }}/${{ inputs.registry_project }}/${{ inputs.image_name }}:latest"
        
        docker build -t "$FULL_IMAGE" -t "$LATEST_IMAGE" -f "${{ inputs.dockerfile }}" "${{ inputs.context }}"
        docker push "$FULL_IMAGE"

