name: 'Process Artifact Manifest'
description: 'Reads artifact-manifest.yaml and pulls all artifacts'
inputs:
  manifest_file:
    description: 'Path to artifact-manifest.yaml'
    required: true
    default: 'artifact-manifest.yaml'
  registry_username:
    required: true
  registry_password:
    required: true

runs:
  using: "composite"
  steps:
    - name: Process Manifest
      shell: bash
      run: |
        if [ ! -f "${{ inputs.manifest_file }}" ]; then
           echo "Manifest file ${{ inputs.manifest_file }} not found!"
           exit 1
        fi
        
        KEYS=$(yq eval '.artifacts | keys | .[]' "${{ inputs.manifest_file }}")
        
        for KEY in $KEYS; do
           IMAGE=$(yq eval ".artifacts[\"$KEY\"].image" "${{ inputs.manifest_file }}")
           TAG=$(yq eval ".artifacts[\"$KEY\"].tag" "${{ inputs.manifest_file }}")
           FILE_PATH=$(yq eval ".artifacts[\"$KEY\"].path" "${{ inputs.manifest_file }}")
           
           echo "Pulling $KEY ($IMAGE:$TAG) to $FILE_PATH"
           
           parts=(${IMAGE//\// })
           REGISTRY=${parts[0]}
           PROJECT=${parts[1]}
           ARTIFACT=${parts[2]}
           
           oras login $REGISTRY -u '${{ inputs.registry_username }}' -p '${{ inputs.registry_password }}'
           mkdir -p "$(dirname "$FILE_PATH")"
           oras pull "$IMAGE:$TAG" -o "$FILE_PATH"
        done

